version: '3.4'
services:
  cache:
    image: redis
    expose: [ 6379 ]
    ports: [ "6379:6379" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  profiles:
    restart: always
    image: mongo
    ports: [ 27017:27017 ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


  mongo-express:
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@profiles:27017/

  users:
    restart: always
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=perfecto
      - POSTGRES_DB=l38rnw3ll!
    ports: ['5432:5432']
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insights -d insightsDb"]
      interval: 10s
      timeout: 5s
      retries: 5